---

- hosts: localhost
  connection: local
  gather_facts: false
  tags: provisioning

  vars:
    instance_type: t2.micro
    security_group: testservers
    image: ami-005bdb005fb00e791
    region: us-west-2
    keypair: customized-key
    count: 1

  vars_files:
    - aws_keys.yml

  tasks:
    - name: Create security group
      ec2_group:
        name: "{{security_group}}"
        description: Test security group
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Launch EC2 Instance
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        group: "{{security_group}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        wait: true
        region: "{{region}}"
        keypair: "{{keypair}}"
        count: "{{count}}"
      register: ec2


    - name: Add newly created instance to host file
      add_host:
        name: "{{item.public_ip}}"
        groups: testservers
      with_items: "{{ec2.instances}}"
      
    - name: Add tag to Instance
      ec2_tag:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        resource: "{{item.id}}"
        region: "{{region}}"
        state: "present"
      with_items: "{{ec2.instances}}"
      args:
        tags:
          Type: testserver

    - name: SSH startup...
      wait_for:
        host: "{{item.public_ip}}"
        port: 22
        state: started
      with_items: "{{ec2.instances}}"

