---

- hosts: local
  connection: local
  gather_facts: false
  vars:
    region: us-west-2
  vars_files:
    - aws_keys.yml
  tasks:
    - name: Gather AWS facts
      ec2_instance_facts:
        region: "{{region}}"
        filters: 
          "tag:Type": "testserver"
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
      register: ec2
#    - debug: var=ec2

    - name: Terminate AWS Instance(s)
      ec2:
        instance_ids: '{{item.instance_id}}'
        state: absent
        region: "{{region}}"
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
      with_items: "{{ec2.instances}}"
